In [1]:
pip install numpy pandas matplotlib scikit-learn openpyxl seaborn

  Obtaining dependency information for matplotlib from https://files.pythonhosted.org/packages/26/5a/27fd341e4510257789f19a4b4be8bb90d1113b8f176c3dab562b4f21466e/matplotlib-3.8.2-cp311-cp311-win_amd64.whl.metadata
  Using cached matplotlib-3.8.2-cp311-cp311-win_amd64.whl.metadata (5.9 kB)
  Obtaining dependency information for seaborn from https://files.pythonhosted.org/packages/7b/e5/83fcd7e9db036c179e0352bfcd20f81d728197a16f883e7b90307a88e65e/seaborn-0.13.0-py3-none-any.whl.metadata
  Using cached seaborn-0.13.0-py3-none-any.whl.metadata (5.3 kB)
Using cached matplotlib-3.8.2-cp311-cp311-win_amd64.whl (7.6 MB)
Using cached seaborn-0.13.0-py3-none-any.whl (294 kB)
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import numpy as np

In [2]:
a = 15

In [3]:
b = 12

In [4]:
c = a + b

In [5]:
c

27

#### numpy

* numerical python - mejoroly work with array called ndarry
* ndarry - n dimensional array
* statistical library comes with many statistical functions and packages
* numpy is the fast processed library built with C compiler
* every numpy array is already compiled with C so that it will take less time to execute
* why numpy developed where python already has list data structure?
* numpy array calculation is done elementwise
* dafault datatype in numpy is float
* it can store string integer also

In [6]:
ls = [1,2,3,4,5,6,8]

In [7]:
ls

[1, 2, 3, 4, 5, 6, 8]

In [8]:
ls[2]

3

In [9]:
arr = np.array([1,2,3,4,5,6,7,8])

In [10]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
arr[2]

3

In [12]:
ls2 = [[1,2,3], [4,5,6], [7,8,9]]
ls2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
arr2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2    # matrix  3 X 3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr2.ndim    # ndim is the number of dimensions

2

In [15]:
ls*2

[1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8]

In [16]:
arr*2

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [17]:
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [18]:
np.array([1,2,3]) + np.array([4,5,6])

array([5, 7, 9])

In [19]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr2.shape    # shape shows number of rows and columns

(3, 3)

In [21]:
arr2.size   # size returns number of element in array

9

In [22]:
arr3 = np.arange(5,67,8)   # start,end,step
arr3

array([ 5, 13, 21, 29, 37, 45, 53, 61])

In [23]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [24]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [25]:
arr4 = np.arange(1,65)

In [26]:
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

In [27]:
arr4.ndim   # in one dimensions array all the number value are column

1

In [28]:
arr4.shape

(64,)

In [29]:
arr4.size

64

In [30]:
np.array([[1,2,3],[4,5,6]]).shape

(2, 3)

In [31]:
a = (10)

In [32]:
type(a)

int

In [39]:
b = 4,5,6

In [38]:
type(b)

tuple

In [40]:
c = 45,

In [41]:
type(c)

tuple

In [42]:
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

In [43]:
arr4.reshape(2,32)  # Reshape used to change dimension of array, while doing it we cannot change size of an array

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64]])

In [44]:
arr4.reshape(4,16)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64]])

In [45]:
arr4.reshape(8,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [46]:
arr4.reshape(16,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [33, 34, 35, 36],
       [37, 38, 39, 40],
       [41, 42, 43, 44],
       [45, 46, 47, 48],
       [49, 50, 51, 52],
       [53, 54, 55, 56],
       [57, 58, 59, 60],
       [61, 62, 63, 64]])

In [47]:
arr4.reshape(-1,1)   # change column to row & row to column

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35],
       [36],
       [37],
       [38],
       [39],
       [40],
       [41],
       [42],
       [43],
       [44],
       [45],
       [46],
       [47],
       [48],
       [49],
       [50],
       [51],
       [52],
       [53],
       [54],
       [55],
       [56],
       [57],
       [58],
       [59],
       [60],
       [61],
       [62],
       [63],
       [64]])