In [1]:
print("Hello NumPy")

Hello NumPy


In [2]:
import numpy as np

In [3]:
print("Best of Luck")

Best of Luck


In [4]:
print("Good Luck")

Good Luck


### NumPy

* Numerical Python - majorely works with array called ndarray
* ndarray - n dimensional array
* Stastical library comes with many statistical functions and packages
* Numpy is the fast processed library built with C compiler
* Every numpy array is alrady compiled with C so that it will take less time to execute
* Why numpy is developed where python already has list data structure?
* numpy array caluculation is done elementwise
* Default datatype in numpy is float
* it can store string, integer also

In [5]:
ls = [1,2,3,4,5,6,8]

In [6]:
ls

[1, 2, 3, 4, 5, 6, 8]

In [7]:
ls[4]

5

In [8]:
arr = np.array([1,2,3,4,5,6,7,8])

In [9]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
arr[4]

5

In [11]:
ls2 = [[1,2,3], [4,5,6], [7,8,9]]
ls2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
arr2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2    # Matrix 3 X 3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arr2.ndim    # ndim is the number of dimension

2

In [17]:
ls*2

[1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8]

In [19]:
arr*2

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [20]:
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [21]:
np.array([1,2,3]) + np.array([4,5,6])

array([5, 7, 9])

In [22]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr2.shape   # Shape shows number of rows and columns

(3, 3)

In [26]:
arr2.size    # Size returns number of element in array

9

In [27]:
arr3 = np.arange(5, 67, 8)
arr3

array([ 5, 13, 21, 29, 37, 45, 53, 61])

In [28]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [29]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [30]:
arr4 = np.arange(1, 65)

In [31]:
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

In [32]:
arr4.ndim

1

In [33]:
arr4.shape

(64,)

In [34]:
arr4.size

64

In [38]:
np.array([[1,2,3],[4,5,6]]).shape

(2, 3)

In [44]:
a = (10,)

In [45]:
type(a)

tuple

In [41]:
b = 4,7,2,6

In [42]:
type(b)

tuple

In [46]:
c = 45,

In [47]:
type(c)

tuple

In [49]:
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

In [50]:
arr4.reshape(2,32)   # Reshape used to change dimension of array, while doing it we cannot change size of an array

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64]])

In [51]:
arr4.reshape(4, 16)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64]])

In [52]:
arr4.reshape(8,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [53]:
arr4.reshape(16, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [33, 34, 35, 36],
       [37, 38, 39, 40],
       [41, 42, 43, 44],
       [45, 46, 47, 48],
       [49, 50, 51, 52],
       [53, 54, 55, 56],
       [57, 58, 59, 60],
       [61, 62, 63, 64]])

In [54]:
arr4.reshape(32,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24],
       [25, 26],
       [27, 28],
       [29, 30],
       [31, 32],
       [33, 34],
       [35, 36],
       [37, 38],
       [39, 40],
       [41, 42],
       [43, 44],
       [45, 46],
       [47, 48],
       [49, 50],
       [51, 52],
       [53, 54],
       [55, 56],
       [57, 58],
       [59, 60],
       [61, 62],
       [63, 64]])

In [55]:
arr4.reshape(64,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35],
       [36],
       [37],
       [38],
       [39],
       [40],
       [41],
       [42],
       [43],
       [44],
       [45],
       [46],
       [47],
       [48],
       [49],
       [50],
       [51],
       [52],
       [53],
       [54],
       [55],
       [56],
       [57],
       [58],
       [59],
       [60],
       [61],
       [62],
       [63],
       [64]])

In [56]:
arr4.reshape(-1,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35],
       [36],
       [37],
       [38],
       [39],
       [40],
       [41],
       [42],
       [43],
       [44],
       [45],
       [46],
       [47],
       [48],
       [49],
       [50],
       [51],
       [52],
       [53],
       [54],
       [55],
       [56],
       [57],
       [58],
       [59],
       [60],
       [61],
       [62],
       [63],
       [64]])